# Generated by Django 2.1.7 on 2026-01-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=40)),
            ],
        ),
    ]
